env:
    MANIFEST: https://github.com/CherishOS/android_manifest.git -b ten
    DEVICE: RMX2020
    OEM: realme
    DT_LINK: https://github.com/SatoruGojo2k23/device_realme_RMX2020-A10.git -b Cherish
    DT_PATH: device/$OEM/$DEVICE
    VT_LINK: https://github.com/SatoruGojo2k23/a11_vendor_realme_RMX2020.git
    VT_PATH: vendor/$OEM/$DEVICE
    KT_LINK: https://github.com/sarthakroy2002/kernel_realme_RMX2020.git -b Q
    PLATFORM: mt6768
    KT_PATH: kernel/$OEM/$DEVICE
    TARGET: bacon
    EXTRA_CMD: export SKIP_ABI_CHECKS=true
    LUNCH_COMBO: cherish_${DEVICE}-userdebug
    OUTPUT: cherishOS*.zip

task:
  name: "Setting Up, Syncing, Building and Uploading..."
  timeout_in: 240m  
  container:
      image: ghcr.io/satorugojo2k23/docker:arch
      cpu: 8
      memory: 32G

  Storage-Checker_script:
      - df -h
      - lsblk
      - ls -l -a -h
  
  Sync_script:
      - echo "============================"
      - echo "Syncing The Sources..."
      - echo "============================"
      - mkdir -p ~/work
      - cd ~/work
      - repo init --depth=1 --no-repo-verify -u $MANIFEST
      - repo sync -c -j8 --force-sync --no-tags --no-clone-bundle
      - git clone --depth=1 $DT_LINK $DT_PATH
      - git clone --depth=1 $KT_LINK $KT_PATH
      - git clone --depth=1 $VT_LINK $VT_PATH
      - echo "============================"
      - echo "Syncing Complete!"
      - echo "============================"

  Build_script:
      - echo "============================"
      - echo "Starting the Build..."
      - echo "============================"
      - cd ~/work
      - $EXTRA_CMD
      - export USE_CCACHE=1
      - export CCACHE_EXEC=/usr/bin/ccache
      - ccache -M 5G
      - . build/envsetup.sh
      - lunch "$LUNCH_COMBO"
      - export TZ=Asia/Dhaka
      - make bacon
     
  Upload_script:
      - echo "============================"
      - echo "Uploading the Build..."
      - echo "============================"
      - cd ~/work
      - cd out/target/product/"$DEVICE"
      - ls -lh
      - pwd
      - chmod 777 *
      - curl --upload-file $(echo $OUTPUT) https://transfer.sh | tee link.txt && echo " "
      - echo " "
      - echo "============================"
      - echo "Build Uploaded!"
      - echo "Please see the link Below-  "
      - echo "----------------------------"
      - cat link.txt && echo " "
      - echo "============================"
        
